### ISSUE TITLE
Skip SauceLabs tests for Pull Requests

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#18]
We've using encrypted env variables for pass SauceLabs access credentials in `.travis.yml` file. For security reasons Travis doesn't decrypt those for Pull Requests (see http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables).

We should check, that if we're building on Travis + this is Pull Request (TRAVIS_SECURE_ENV_VARS or TRAVIS_PULL_REQUEST), then skip these tests.

**Comment by stof** [comment]
Using ``TRAVIS_SECURE_ENV_VARS`` for that, as this is what impacts the build actually

**Comment by aik099** [comment]
As I've written in task description. But we also should add that variable (commented-out) to `phpunit.xml.dst` because without it when running tests locally the SauceLabs related ones will also be skipped.

**Comment by stof** [comment]
Even simpler: skip the tests if ``SAUCE_USERNAME`` and ``SAUCE_ACCESS_KEY`` are not defined)

**Comment by aik099** [comment]
Ha, maybe tests are failing now because Travis isn't decrypting them for PR :) Before I've did direct pushes and all worked. Ticky.

If we want SauceLabs to run we need to expose SauceLabs credentials publicly. That would allow everybody to use them to run their own tests on that opensource account, but I'm not sure if anybody will do that anyway,
