### ISSUE TITLE
Remove dependency on Pimple

### ISSUE THREAD

**Issue by adambro** [minkphp/phpunit-mink#21]
I've tried to use phpunit-mink with my Silex application, but stumbled upon a roadblock. Silex 1.2 (current stable) uses Pimple ~1.0 while phpunit-mink requires Pimple 2.0 or upper. Composer is not able to resolve the conflicts, as Pimple public interface has changed.

My idea is to remove dependency on Pimple in Composer to avoid conflicts. Some ways I see it can be done:
* copy Pimple code into phpunit-mink repo (quick fix, but hacky)
* use git submodule to attach Pimple 2.0 code (not sure if Composer supports that)
* refactor DIContainer so it does not depend on Pimple functionality

Personally I'm in favor of Dependency Inversion, but libraries depending on Dependency Injection Container are hard to integrate due to such issues. Let me know your thoughts.

**Comment by aik099** [comment]
@adambro I've decided to reopen your ticket and redo everything according to plan from https://github.com/minkphp/phpunit-mink/issues/21#issuecomment-62111560 except that I'll call vendor "PimpleCopy" instead of "aik099" because I'm not creating it theoretically.
