### ISSUE TITLE
Migration to "minkphp" organization

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#27]
Recently the https://github.com/minkphp organization were created and all Mink-related repositories were moved there. I believe this repository is quite Mink-related as well to be moved there as well.

Here are some specifics about this repo:

1. it uses it's own documentation http://phpunit-mink.readthedocs.org/en/latest/ so no shared documentation with https://mink.readthedocs.org/en/latest/ I guess
2. it uses own coding standard (https://github.com/aik099/CodingStandard) which uses TABs for indentation
3. it uses my personal accounts (encrypted using current repo ID in `.travis.yml`) for testing SauceLabs and BrowserStack services (I'm not sure if either of services allows for personal open-source account usage in another GitHub organization)
4. because PHP_CodeSniffer on Scrutinizer CI is still 1.5 the inspection fails on Fatal Error (because coding standard uses classes added in PHP_CodeSniffer 2.0)
5. the package name on Composer will stay the same for existing users to be happy
6. probably need to contact both Scrutinizer CI and Coveralls.IO to make them rename the repo or otherwise I will loose all the past inspections

//cc @stof

**Comment by stof** [comment]
1. I suggest keeping the doc separate at least for now (unless you prefer having it in the main doc)

2. Do you feel strongly about these coding standards or would you consider switching to spaces for the indentation to be consistent accross Mink repos ? Note that I don't feel too strongly on this, given I will probably let you maintain the repo even after the move.

3. AFAICT, SauceLabs open source accounts are tied to a repository (they ask the repo URL when subscribing), but I'm not sure about it. Anyway, it should be possible to subscribe again for the minkphp organization if this is needed

4. Maybe we should disable the usage of the PHPCS config on Scrutinizer for now to make inspections working again (it is better to miss the CS reports than to miss the full report IMO)

5. agreed. This is already what we did for Mink repos. The PHP namespace has also been kept for them. 

6. For scrutinizer, it is indeed possible to ask their support. For coveralls, I don't know how it works. It might be worth investigating before the move.

**Comment by aik099** [comment]
> I suggest keeping the doc separate at least for now (unless you prefer having it in the main doc)

OK. No change here then.

> Do you feel strongly about these coding standards or would you consider switching to spaces for the indentation to be consistent across Mink repos ?

I can switch to PSR2 of course if you like. But I created my own coding standard because PSR2 leaves too much formatting to user consideration, which I don't like. That's why I created my own standard that enforces pretty much everything. Now with auto-fixing feature of PHP_CodeSniffer majority of these violations can be fixed automatically so I'm even more happier.

There is no such TABs/SPACEs switch (or any switch) in coding standard because it's meant to be followed in 100% cases and not in 99% cases :wink: . I create separate branch and change `ruleset.xml` in there, which is problematic to maintain because I do change main standard quite often (fixing bugs, adding more restrictions) and merging to that other branch is just an extra step.

> AFAICT, SauceLabs open source accounts are tied to a repository (they ask the repo URL when subscribing), but I'm not sure about it. Anyway, it should be possible to subscribe again for the minkphp organization if this is needed

OK. Then we need to have some kind of organization-wide e-mail that we can use to register these new accounts.

> Maybe we should disable the usage of the PHPCS config on Scrutinizer for now to make inspections working again (it is better to miss the CS reports than to miss the full report IMO)

Better to see Fatal Error and know that Scrutinizer CI is failing, then don't check coding standard IMO.

> For scrutinizer, it is indeed possible to ask their support. For coveralls, I don't know how it works. It might be worth investigating before the move.

Where do I write to request that move?

**Comment by aik099** [comment]
Then I'll proceed with a move. I'll update Scrutinizer CI and Coveralls IO integrations eventually.

**Comment by stof** [comment]
> I can switch to PSR2 of course if you like. But I created my own coding standard because PSR2 leaves too much formatting to user consideration, which I don't like. That's why I created my own standard that enforces pretty much everything. Now with auto-fixing feature of PHP_CodeSniffer majority of these violations can be fixed automatically so I'm even more happier.

For other repos, I'm actually following the Symfony2 standards (which are additional rules on top of PSR-2). I'm totally fine with being stricter than PSR-2, but IMO, it is better to build on top of PSR-2 for custom stricter standards, so that all tools relying on PSR-2 can already make a decent job.

> Better to see Fatal Error and know that Scrutinizer CI is failing, then don't check coding standard IMO.

Scrutinizer is able to check coding standards on its own too, even though it might miss some of your rules. But more important, this fatal error means you are also missing all the static analysis of PhpAnalyzer

> Where do I write to request that move?

For Scrutinizer, you need to use the ``?`` icon on the bottom right of the interface to contact the support. But this needs to be done after the move

**Comment by stof** [comment]
When migrating, don't forget to update the repo URL on packagist (login on packagist and then click the Edit button on the package page)

**Comment by aik099** [comment]
GitHub says that transfer failed because I don't have admin rights on "minkphp" user.

**Comment by stof** [comment]
I switched the "Core team" team to admin access. Can you try again ?

**Comment by aik099** [comment]
That worked. You can switch back now. Hopefully I would retain push access to that new repo after admin right removal.

**Comment by stof** [comment]
You will, given that the team still has write access

**Comment by stof** [comment]
Remaining tasks:

- [ ] update the URL on packagist
- [ ] update the url RTD project
- [ ] fork back to your account to preserve download URLs for locked dependencies (and to contribute)
- [ ] request the scrutinizer move
- [ ] update badge URLs in the readme
- [ ] check the testsuite setup for saucelabs and browserstack (I just triggered a Travis btw so check first whether it works fine)
- [ ] request the coveralls move (or drop it in favor of collecting coverage on Scrutinizer instead, like for other Mink repos)

**Comment by aik099** [comment]
> For Scrutinizer, you need to use the ? icon on the bottom right of the interface to contact the support. But this needs to be done after the move

I don't see such icon. Can you post a screenshot with it's location?

**Comment by aik099** [comment]
Now it suddenly appeared out of nowhere. Large white question in blue square.

**Comment by stof** [comment]
@aik099 not waiting for the JS to load ?

**Comment by aik099** [comment]
I swear I've never seen this icon before. I have some extension in my browser, that is blocking all tracking codes (like Facebook/Twitter buttons and such). Apparently the support script that showed that button was one of them. I've temporarily disabled it and that allowed the button to appear.

**Comment by aik099** [comment]
> update the homepage in the composer.json

I've did that, but apparently the Packagist hook is no longer working. Can you please add/update Packagist hook to it will track all pushes to the repo?

**Comment by stof** [comment]
> I've did that, but apparently the Packagist hook is no longer working. Can you please add/update Packagist hook to it will track all pushes to the repo?

I found the issue. The Packagist hook service allows to guess the Packagist username from the repo owner name, and it was the case for your repo. Because of the move, the guessing was not working anymore. I added the Packagist username explicitly and it works again

**Comment by aik099** [comment]
At least now I know why I have same issue when I've moved "aik099/qa-tools" into "qa-tools/qa-tools". Thanks.

**Comment by stof** [comment]
I updated the badges in the readme (the scrutinizer badge is broken until the repo is actually moved on their side)

**Comment by aik099** [comment]
> check the testsuite setup for saucelabs and browserstack (I just triggered a Travis btw so check first whether it works fine)

It's passing (I've updated SauceLabs access keys), but apparently something else is wrong on SauceLabs website because I'm getting weird errors. I've reported it separately in #29.

**Comment by aik099** [comment]
> update the link to this repo in the Mink documentation

Is https://github.com/minkphp/docs/blob/master/index.rst the only file, that needs changing?

**Comment by stof** [comment]
yeah, there is a single link to it.

**Comment by stof** [comment]
> check the testsuite setup for saucelabs and browserstack

is there anything actually related to browserstack in the Travis setup ?

**Comment by aik099** [comment]
> is there anything actually related to browserstack in the Travis setup ?

Nope. The PHP part was written some time ago (see https://github.com/minkphp/phpunit-mink/blob/master/library/aik099/PHPUnit/APIClient/BrowserStackAPIClient.php), but without account to BrowserStack I wasn't able to test it. After talking with BrowserStack support I was able to create OpenSource account, but then I hadn't much free time to test the integration.

**Comment by aik099** [comment]
Guys from Scrutinizer CI haven't responded in 7 hours now. I wonder why message in support panel says, that they respond within an hour.

// cc @scrutinizer-ci

**Comment by stof** [comment]
I tried pinging @schmittjoh on Twitter: https://twitter.com/Stof70/status/553239174275694593

**Comment by aik099** [comment]
And it was done: https://scrutinizer-ci.com/g/minkphp/phpunit-mink/ .

**Comment by aik099** [comment]
Now the only thing left is coveralls. Their repo move feature doesn't seem to work. I press move button and nothing happens. I've created support ticket on their website.

**Comment by stof** [comment]
Any news from coveralls ?

**Comment by aik099** [comment]
Absolutely none. I've also posted to Twitter but no lock. It's very unprofessional from their website to create non-working repo rename feature and then never reply to issues people are having with it.

I have no idea how else can I get their attention to my problem.

**Comment by stof** [comment]
What do you think about uploading the code coverage to Scrutinizer instead (as done for all other Mink repos) ? We would not have the history of course, but it is better than nothing

**Comment by aik099** [comment]
I'm reporting code coverage to both places in any case. But Coveralls.Io being coverage-specific service is better at displaying changes over time then Scrutinizer CI.

So it's a matter of showing different badge :) We can switch badge and later, when Coveralls.Io will fix repo move feature we'll revert the change.

**Comment by aik099** [comment]
All done.
