### ISSUE TITLE
Support Pimple 3.0

### ISSUE THREAD

**Issue by stof** [minkphp/phpunit-mink#28]
Pimple 3 is stable (it is basically Pimple 2 without the BC layer for the old ``Pimple`` name as this BC layer was impossible to provide in the C extension).
The requirement should allow using it (if the library uses the ``Pimple\Container`` name everywhere, it should be a matter of changing the constraint to ``~2|~3``)

**Comment by aik099** [comment]
I had one issue in past (see #21) where main project was dependent on Pimple 1.0 and wanted to use PHPUnit-Mink. Composer could not find common dependency and ended up not installing anything.

If we don't take this into consideration, then upgrading to Pimple 3.0 is indeed very simple process.

**Comment by stof** [comment]
Well, depending on 2.0 only means that both 1.0 and 3.0 projects are not well supported (so all Silex versions for instance). Supporting both 2.0 and 3.0 together is really easy (the only BC break in 3.0 is the removal of the ``Pimple`` class alias).

Adding sypport for Pimple 1 is more work. It would require me to review the usages of Pimple first to see how this could be done (I don't know this library yet)

**Comment by aik099** [comment]
The major difference between Pimple 1 and 2 is that:

* in Pimple 1 the default behavior is not to share
* in Pimple 2+ the default behavior is to share

To overcome this an extra layer needs to be created over Pimple class to account for that. Unfortunately I don't know how to we determine what Pimple version is being used to apply/not to apply the patch.

But you can update dependency (via PR) anyway and see if any of a tests fails.

**Comment by stof** [comment]
@aik099 ``class_exists('Pimple') && method_exists('Pimple', 'share')`` will detect Pimple 1 (feature detection FTW)

**Comment by aik099** [comment]
I've created PR according to your original proposal. I think that investing time in Pimple 1.0 compatibility would pay off if we'll have more Pimple 1.0 users.
