### ISSUE TITLE
Inline "SessionFactory" class

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#48]
After #12 is implemented the session driver creation is moved away from `SessionFactory` class to the corresponding driver factories. And the `SessionFactory` only has 1 line long method called `createSession`:
![phpunitmink_smallsessionfactory](https://cloud.githubusercontent.com/assets/1277526/6764271/71a85f1a-cfb1-11e4-8a16-09289ba53af0.png)

The only class using that method is `IsolatedSessionStrategy` that can create/start sessions. I propose, that we:
- remove `ISessionFactory` interface
- remove `SessionFactory` class
- inline `SessionFactory::createSession` method into `IsolatedSessionStrategy::session` method

**Comment by stof** [comment]
:+1:
