### ISSUE TITLE
baseUrl not working

### ISSUE THREAD

**Issue by parhamdoustdar** [minkphp/phpunit-mink#51]
The baseUrl I set in the static `$browsers` variable does not have any effect. Take this example:

```php
<?php
namespace AppBundle\Tests\Controller;

use aik099\PHPUnit\BrowserTestCase;

class WhateverControllerTest extends BrowserTestCase
{
    
    public static $browsers = [
        [
            'driver' => 'selenium2',
            'baseUrl' => 'http://www.google.com',
            'port' => 8643
        ]
    ];
    
    public function testAbc()
    {
        $this->getSession()->visit('/');
        die($this->getSession()->getPage()->getContent());
    }
    
}

?>
```

This gives me an output like this:

```
<html><head></head><body></body></html>
```

However, if I change the argument I pass to `visit()` to something like `http://www.google.com` instead, everything works as expected.

**Comment by aik099** [comment]
> The baseUrl I set in the static $browsers variable does not have any effect.

Documentation doesn't really say, that `baseUrl` would be prepended to every visited url. It's surely doesn't work like similar setting in `MinkExtension` of `Behat`.

>  $this->getSession()->visit('/');

In this code, the ` $this->getSession()` returns the Mink session directly and since that point it's impossible for PHPUnit-Mink to alter anything that you pass (e.g. to `visit` method call).

The `baseUrl` setting here is to specify the root url of the tested website, that will be opened before testing is started. It's only used when remote code coverage is collected because we need to set some cookies before user opens any page.

**Comment by parhamdoustdar** [comment]
Thanks for the explanation, @aik099. Isn't there a way to have a baseUrl like that of `MinkExtension`? Also, you may want to consider documenting that this `baseUrl` is different than the one in Mink?

**Comment by aik099** [comment]
> Isn't there a way to have a baseUrl like that of MinkExtension

In the MinkExtension you'll also have `$this->getSession()` method and calling `->visit(` on it also won't prepend `baseUrl`. But MinkExtension is extension to Behat which allows to take parse Gherkin feature context steps (where you don't put any PHP) and can prepend anything anywhere. There is no such extra layer here I'm afraid.

If you're missing that abstraction layer in PHPUnit-Mink, then I can recommend http://www.qa-tools.io/ . It's a standalone library, using Mink, that's purpose is to use PageObject pattern in PHP. It uses annotations in DocBlocks to describe what pages you have on website and what elements are used on each page. And it has `baseUrl` option that works exactly as you think it is by allowing to use relative urls.

Another option maybe is to add `->visitRelativeUrl` to test case, but I'm not sure if that's a good idea.

> Also, you may want to consider documenting that this baseUrl is different than the one in Mink?

Ha, it's not different than Mink. It is Mink without any extras, like Behat/MinkExtension.

**Comment by parhamdoustdar** [comment]
Ah, got it now. Thanks a lot.
