### ISSUE TITLE
Switching to 1st opened window in shared session strategy doesn't work

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#62]
The shared session strategy is supposed to switch focus to 1st opened window in the session before each test. This is done by specifying empty window name to the `Session::switchToWindow` call of the Mink library.

I'm not sure anymore that it's the correct approach.

**Comment by aik099** [comment]
@stof , do you know if there is any cross-Mink-driver way to switch to 1st opened window in session?

**Comment by stof** [comment]
I have no idea. I never used the window switching

**Comment by aik099** [comment]
Do you know how it's solved in MinkExtension? If I understood correctly, then:

* same browser window is shared across several scenarios
* after each scenario ends the session soft reset is done (cookies erased), but browser window stays open

In that case if one scenario opens a popup, then another one will continue to do it's stuff in that popup. Is this really happening that way. If so I wonder why this never created problems for anybody.

**Comment by aik099** [comment]
Turns out we (at Mink) have a test for that in `WindowTest` class. It's working in Firefox, but in Chrome gives this error:

```
1) Behat\Mink\Tests\Driver\Js\WindowTest::testWindow
WebDriver\Exception\UnknownError: unknown error: 'name' must be a nonempty string
  (Session info: chrome=46.0.2490.71)
  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.10.5 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1 milliseconds
Build info: version: '2.48.2', revision: '41bccdd', time: '2015-10-09 19:59:12'
System info: host: 'alex-mbp', ip: '192.168.1.6', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.7.0_60'
Session ID: d3b715d7e55ea78b3795bbdb2bb9b2ce
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=MAC, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/var/folders/zr/z961h7s124z_qq5s4c4_j4000000gn/T/.org.chromium.Chromium.kQz6cz}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=46.0.2490.71, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]

.../vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:155
.../vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php:140
.../vendor/instaclick/php-webdriver/lib/WebDriver/Session.php:273
.../src/Selenium2Driver.php:407
.../vendor/behat/mink/src/Session.php:304
.../vendor/behat/mink/driver-testsuite/tests/Js/WindowTest.php:17
```

Seems to be a bug in ChromeDriver, because I'm also getting this error, when running tests on BrowserStack via Chrome on #61

**Comment by stof** [comment]
> Do you know how it's solved in MinkExtension?

this is currently not solved

**Comment by stof** [comment]
> Seems to be a bug in ChromeDriver

I suggest reporting the bug to ChromeDriver then

**Comment by aik099** [comment]
Reported as https://code.google.com/p/chromedriver/issues/detail?id=1245 .

**Comment by aik099** [comment]
The issue has been fixed on ChromeDriver side and will be available with next release.
