### ISSUE TITLE
Create CHANGELOG.md file

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#66]
See http://keepachangelog.com/ .

**Comment by stof** [comment]
As we post the changelog in github releases, it is already better than some projects though.

**Comment by aik099** [comment]
They were some discussions in the community which one is better to use GitHub release descriptions or write single changelog.md file. I use both for my projects and just copy-paste relevant part of changelog.md file to the release description.

**Comment by stof** [comment]
I also use both in Mink projects
