### ISSUE TITLE
Some tests are marked as risky

### ISSUE THREAD

**Issue by stof** [minkphp/phpunit-mink#71]
See https://travis-ci.org/minkphp/phpunit-mink/jobs/90588427

**Comment by aik099** [comment]
I know, but I have no idea how to avoid that when you're testing PHPUnit extension using PHPUnit itself.

**Comment by stof** [comment]
PHPUnit has a way to mark tests as being covering a testcase: https://github.com/phpspec/prophecy-phpunit/blob/master/Tests/ProphecyTestCaseTest.php#L15 This allows calling testcase methods from inside your testcase.

Ideally, these tests should be run in a separate process, to avoid defining the constant for all the other tests

**Comment by aik099** [comment]
I've created a PR, that is ready for review.
