### ISSUE TITLE
Notice, when used with PHPUnit 5

### ISSUE THREAD

**Issue by dz0ny** [minkphp/phpunit-mink#77]
```
PHP Strict standards:  Declaration of aik099\PHPUnit\BrowserTestCase::onNotSuccessfulTest() should be compatible with PHPUnit_Framework_TestCase::onNotSuccessfulTest($e) in /home/travis/build/niteoweb/bimt-salespages/vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php on line 33

{
  "name": "niteoweb/bimt-salespages",
  "require": {
    "php": "~5.6.0",
    "raven/raven": "^0.13.0"
  },
  "require-dev": {
    "heroku/heroku-buildpack-php": "*",
    "squizlabs/php_codesniffer": "*",
    "aik099/phpunit-mink": "^2.1",
    "phpunit/phpunit": "^5.1"
  },
  "minimum-stability": "stable",
  "config": {
    "bin-dir": "bin/"
  }
}
```

The difference is in: `protected function onNotSuccessfulTest(Exception $e)` vs `protected function onNotSuccessfulTest($e)`.

**Comment by aik099** [comment]
Actually there is more to it. In there PHPUnit 5.x the declaration of that method was changed, but if we change it here as well, then all building using other PHPUnit version will fail.

The solution would be to use trick from Mink's PR addressing same issue in driver test suites: https://github.com/minkphp/Mink/pull/687 :

1. create 2 unit test classes (one for PHPUnit 4.x and another one for PHPUnit 5.x+)
2. only define one of them based on PHPUnit version used
3. extend `BrowserTestCase` from that class

**Comment by aik099** [comment]
@dz0ny , any updates?

**Comment by dz0ny** [comment]
No longer working on this, so no idea...

**Comment by aik099** [comment]
@GeeH, I see from Twitter (https://twitter.com/GeeH/status/806462394239221760), that you've having this issue. I would really appreciate if you'll able to send a PR with a fix as discussed in https://github.com/minkphp/phpunit-mink/issues/77#issuecomment-179702937. That would more of a copy/paste from @stof solution in https://github.com/minkphp/Mink/pull/687.

**Comment by GeeH** [comment]
Thanks, it's worth noting that this is reported as happening on PHP 5, but I am using PHP 7.1.

**Comment by aik099** [comment]
It was reported for PHPUnit 5.x, not for PHP 5.x 😉  . Since PHPUnit 5.x can run on PHP 7.x as well the problem happens in there too.

**Comment by GeeH** [comment]
What a fool I feel.

**Comment by aik099** [comment]
No worries.

**Comment by stof** [comment]
Btw, PHPUnit 5.x is even a requirement for PHP 7 (PHPunit 4.8 does not officially support PHP 7, and is unable to mock scalar or nullable typehints for instance)

**Comment by cweiske** [comment]
As of today, the latest released version is v2.2.0 which does not contain this patch and thus still emits the warning.

**Comment by aik099** [comment]
Yeah, I know. I was waiting to see if anyone can make changes to be PHPUnit 6.x compatible and then make a release.

**Comment by cweiske** [comment]
I think 6.x compatibility is a bigger task, and that should not hinder the delivery of small bugfixes.

**Comment by aik099** [comment]
Small bugfixes that introduce major BC breaks 😄 , like constructor signature change in https://github.com/minkphp/phpunit-mink/pull/99.

@stof , is this a BC break or we should ignore it?
