### ISSUE TITLE
Create BrowserStackBrowserConfiguration

### ISSUE THREAD

**Issue by aik099** [minkphp/phpunit-mink#8]
Right now the following 2 browser configurations are supported:
* regular (browser is running on local machine)
* SauceLabs (browser is running on SauceLabs virtual machine)

Now BrowserStack also supports Selenium through WebDriver protocol (see https://www.browserstack.com/automate/php) and we need to add browser configuration to use it.

**Comment by stof** [comment]
@aik099 should this be closed or is it still incomplete ?

**Comment by aik099** [comment]
I guess I haven't closed this because code is there, but I never tested that it works.
