### ISSUE TITLE
Backport each fix into earlier releases

### ISSUE THREAD

**Issue by shmax** [minkphp/phpunit-mink#88]
Recently, @eclipxe13 opened this fix for a PHP 7.2 deprecation of `each`: 
https://github.com/sebastianbergmann/phpunit/pull/2536/files

Do you have any mechanism or process for backporting this kind of thing to your other releases? I maintain a project that still supports PHP versions all the way back to 5.4, but I would also like to support PHP 7.

Let me know if there is anything I can do to help. Thank you!

**Comment by shmax** [comment]
I think I opened this against the wrong repo; sorry!

**Comment by aik099** [comment]
That's a pity, I mean deprecation of `each`, because I use it like this usually:

```php
$items = array('key' => 'value');
list($key, $value) = each($items);
```

without that I'd have to create 2 lines longer construct:

```php
$items = array('key' => 'value');
foreach ( $items as $key => $value ) {
    break;
}
```

**Comment by shmax** [comment]
Evidently it's more than 10 times slower: https://wiki.php.net/rfc/deprecations_php_7_2

**Comment by aik099** [comment]
When used in cycles yes, but I only need 1st key/value pair. Is there any equivalent one-line command for that?

**Comment by stof** [comment]
@aik099 you could do this:

```php
$key = key($items);
$value = current($items);
```

And then, you can use a list trick to keep in a one-liner if you really want

**Comment by aik099** [comment]
Or extract that to utility class.

I guess deprecation of `each` was done to prevent people using it instead of `foreach`. But as a side effect people not using it as `foreach` replacement got hit by deprecation notice on each use.
