### ISSUE TITLE
Why do I have to set PHPUNIT_MINK_TUNNEL_ID as environment variable?

### ISSUE THREAD

**Issue by robertfausk** [minkphp/phpunit-mink#91]
It seems I have to do a
```PHP
putenv('PHPUNIT_MINK_TUNNEL_ID=' . $tunnel_id);
```
before creating my browser configuration which feels a little bit weird for me.

**Comment by aik099** [comment]
You don't. Creating a tunnel is an optional feature of both SauceLabs and BrowserStack.

**Comment by aik099** [comment]
The env-way is created mostly for build servers, where:

* several tunnels can exist in parallel (usual stuff, when running tests on multiple PHP versions/browsers from build server like Travis CI)
* tunnel is linked to IP starting it and attempt to use same tunnel from multiple IPs might fail

If you'll look at actual places where this env variable is used, then you'll see that in fact it's used exactly to populate desired capabilities in current browser configuration.

## Sauce Labs

https://github.com/minkphp/phpunit-mink/blob/master/library/aik099/PHPUnit/BrowserConfiguration/SauceLabsBrowserConfiguration.php#L57-L59

```php
$desired_capabilities['tunnel-identifier'] = getenv('PHPUNIT_MINK_TUNNEL_ID');
```

## BrowserStack

https://github.com/minkphp/phpunit-mink/blob/master/library/aik099/PHPUnit/BrowserConfiguration/BrowserStackBrowserConfiguration.php#L59-L62

```php
$desired_capabilities['browserstack.local'] = 'true';
$desired_capabilities['browserstack.localIdentifier'] = getenv('PHPUNIT_MINK_TUNNEL_ID');
```

So you can that as well.
