### ISSUE TITLE
Call to a member function getDefaultSessionStrategy() on null 

### ISSUE THREAD

**Issue by umpirsky** [minkphp/phpunit-mink#96]
Got:

```
Fatal error: Uncaught Error: Call to a member function getDefaultSessionStrategy() on null in vendor/aik099/phpunit-mink/library/aik099/PHPUnit/BrowserTestCase.php:272
```

Code:

```
class MyTestCase extends BrowserTestCase
{
    public static $browsers = [[
        'driver' => 'selenium2',
            'host' => 'localhost',
            'port' => 4444,
            'browserName' => 'firefox',
            'baseUrl' => 'http://www.google.com',
    ]];
}
```

Using `aik099/phpunit-mink (dev-master 1bec92d)`

**Comment by aik099** [comment]
1. what version (or master branch) of this library?
2. what version of php?
3. what version of phpunit?
4. happens on latest release of this library as well?
5. please attach backtrace as well.

**Comment by umpirsky** [comment]
> what version (or master branch) of this library?

See description. ;)

> what version of php?

7.1.6

> what version of phpunit?

5.7.21

> happens on latest release of this library as well?

Yes.

> please attach backtrace as well.

Sorry, don't have it, and it will take much time to reproduce again since I gave up using it.

**Comment by aik099** [comment]
How does your tests look like?

**Comment by aik099** [comment]
Have you tried with PHP 7.0 (it's being used on Travis CI)?

P.S.
I wasn't able to get PHP 7.1 installed/compiled locally due Segmentation fault error.

**Comment by aik099** [comment]
https://travis-ci.org/minkphp/phpunit-mink/jobs/272367995 - tests passing on PHP 7.1, so there must something unusual going on causing that error for you.

**Comment by umpirsky** [comment]
The test was just simple `->getSession()->visit()`.

**Comment by aik099** [comment]
There are several tests like that in test suite as well. And now I've updated Travis CI to run them on PHP 7.1. All working fine there. I really have no idea why you're getting that error.
