### ISSUE TITLE
Argument 1 passed to BrowserTestCase::onNotSuccessfulTestCompatibilized() must be an instance of Exception

### ISSUE THREAD

**Issue by umpirsky** [minkphp/phpunit-mink#97]
```
TypeError: Argument 1 passed to aik099\PHPUnit\BrowserTestCase::onNotSuccessfulTestCompatibilized() must be an instance of Exception, instance of Error given, called in vendor/aik099/phpunit-mink/library/aik099/PHPUnit/AbstractPHPUnitCompatibilityTestCase.php on line 37
```

This may happen on error.

**Comment by aik099** [comment]
1. what version (or `master` branch) of this library?
2. what version of php?
3. what version of phpunit?

The #89 was fixing PHPUnit 5 compatibility. Unfortunately it's impossible to have PHPUnit 6 compatibility (as discussed in #93), because library is using Mockery internally and Mockery isn't compatible with PHPUnit 6.

Probably if we rewrite test suite using Prophecy, then PHPUnit 6 compatibility won't be an issue.

**Comment by umpirsky** [comment]
@aik099 See https://github.com/minkphp/phpunit-mink/issues/96#issuecomment-327292964.

**Comment by aik099** [comment]
Have you tried with PHP 7.0 (it's being used on Travis CI).

P.S.
I wasn't able to get PHP 7.1 installed/compiled locally due Segmentation fault error.

**Comment by umpirsky** [comment]
No, just PHP 7.1.

**Comment by aik099** [comment]
I've updated Travis CI to run them on PHP 7.1. All working fine there. I really have no idea why you're getting that error.

**Comment by umpirsky** [comment]
OK, no worries, if I ever try it again, I'll reopen with more details, thanks!

**Comment by cweiske** [comment]
I have the same problem with phpunit 5.7.22, PHP 7.0.22 and phpunit-mink git master as of today when using a non-existing method:

    $session->find('id_or_name', 'email');

Error message:

> Error: Call to undefined method aik099\PHPUnit\Session\SessionProxy::find()

In PHP7, this are no exceptions anymore but of type `Error`, see http://php.net/manual/en/language.errors.php7.php

**Comment by aik099** [comment]
Bad news. @cweiske , do you have any idea how test suite can be updated to test actual different PHPUnit version compatibility with PHP versions?

**Comment by cweiske** [comment]
`.travis.yml`'s build matrix could have different phpunit versions in an ENV variable, and that variable is then used to `composer require phpunit/phpunit:$PHPUNIT` in `script`.

https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix

**Comment by aik099** [comment]
On Travis CI there is already different PHPUnit version (as phar) is used for different PHP version. For example PHP 7.x uses PHPUnit 6.x, but PHP 5.6 is using PHPUnit 5.x.

To replicate the issue you're having we actually need to have test, like yours where call to non-existing method is made and validate that error is property catched and then test will pass. I have no idea how to do this.

**Comment by cweiske** [comment]
PHPUnit's TestCase is different in versions 4, 5 and 6. We need adjustments to 
`AbstractPHPUnitCompatibilityTestCase` for each of them:

# 4.8
    protected function onNotSuccessfulTest(Exception $e)
https://github.com/sebastianbergmann/phpunit/blob/4.8/src/Framework/TestCase.php#L1966

# 5.7
    protected function onNotSuccessfulTest($e)
https://github.com/sebastianbergmann/phpunit/blob/5.7/src/Framework/TestCase.php#L2162

# 6.4
    protected function onNotSuccessfulTest(Throwable $t)
https://github.com/sebastianbergmann/phpunit/blob/6.4/src/Framework/TestCase.php#L2160
